/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedDashboardTagsIndexRouteImport } from './routes/(protected)/dashboard/tags/index'
import { Route as protectedDashboardSettingsIndexRouteImport } from './routes/(protected)/dashboard/settings/index'
import { Route as protectedDashboardFoldersIndexRouteImport } from './routes/(protected)/dashboard/folders/index'
import { Route as protectedDashboardTagsTagNameRouteImport } from './routes/(protected)/dashboard/tags/$tagName'
import { Route as protectedDashboardFoldersAddRouteImport } from './routes/(protected)/dashboard/folders/add'
import { Route as protectedDashboardBookmarksAddRouteImport } from './routes/(protected)/dashboard/bookmarks/add'
import { Route as protectedDashboardFoldersIdIndexRouteImport } from './routes/(protected)/dashboard/folders/$id/index'
import { Route as protectedDashboardFoldersIdEditRouteImport } from './routes/(protected)/dashboard/folders/$id/edit'
import { Route as protectedDashboardBookmarksIdEditRouteImport } from './routes/(protected)/dashboard/bookmarks/$id/edit'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardTagsIndexRoute =
  protectedDashboardTagsIndexRouteImport.update({
    id: '/dashboard/tags/',
    path: '/dashboard/tags/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedDashboardSettingsIndexRoute =
  protectedDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedDashboardFoldersIndexRoute =
  protectedDashboardFoldersIndexRouteImport.update({
    id: '/dashboard/folders/',
    path: '/dashboard/folders/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedDashboardTagsTagNameRoute =
  protectedDashboardTagsTagNameRouteImport.update({
    id: '/dashboard/tags/$tagName',
    path: '/dashboard/tags/$tagName',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedDashboardFoldersAddRoute =
  protectedDashboardFoldersAddRouteImport.update({
    id: '/dashboard/folders/add',
    path: '/dashboard/folders/add',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedDashboardBookmarksAddRoute =
  protectedDashboardBookmarksAddRouteImport.update({
    id: '/dashboard/bookmarks/add',
    path: '/dashboard/bookmarks/add',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedDashboardFoldersIdIndexRoute =
  protectedDashboardFoldersIdIndexRouteImport.update({
    id: '/dashboard/folders/$id/',
    path: '/dashboard/folders/$id/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedDashboardFoldersIdEditRoute =
  protectedDashboardFoldersIdEditRouteImport.update({
    id: '/dashboard/folders/$id/edit',
    path: '/dashboard/folders/$id/edit',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedDashboardBookmarksIdEditRoute =
  protectedDashboardBookmarksIdEditRouteImport.update({
    id: '/dashboard/bookmarks/$id/edit',
    path: '/dashboard/bookmarks/$id/edit',
    getParentRoute: () => protectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/dashboard/bookmarks/add': typeof protectedDashboardBookmarksAddRoute
  '/dashboard/folders/add': typeof protectedDashboardFoldersAddRoute
  '/dashboard/tags/$tagName': typeof protectedDashboardTagsTagNameRoute
  '/dashboard/folders': typeof protectedDashboardFoldersIndexRoute
  '/dashboard/settings': typeof protectedDashboardSettingsIndexRoute
  '/dashboard/tags': typeof protectedDashboardTagsIndexRoute
  '/dashboard/bookmarks/$id/edit': typeof protectedDashboardBookmarksIdEditRoute
  '/dashboard/folders/$id/edit': typeof protectedDashboardFoldersIdEditRoute
  '/dashboard/folders/$id': typeof protectedDashboardFoldersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/dashboard/bookmarks/add': typeof protectedDashboardBookmarksAddRoute
  '/dashboard/folders/add': typeof protectedDashboardFoldersAddRoute
  '/dashboard/tags/$tagName': typeof protectedDashboardTagsTagNameRoute
  '/dashboard/folders': typeof protectedDashboardFoldersIndexRoute
  '/dashboard/settings': typeof protectedDashboardSettingsIndexRoute
  '/dashboard/tags': typeof protectedDashboardTagsIndexRoute
  '/dashboard/bookmarks/$id/edit': typeof protectedDashboardBookmarksIdEditRoute
  '/dashboard/folders/$id/edit': typeof protectedDashboardFoldersIdEditRoute
  '/dashboard/folders/$id': typeof protectedDashboardFoldersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/dashboard/bookmarks/add': typeof protectedDashboardBookmarksAddRoute
  '/(protected)/dashboard/folders/add': typeof protectedDashboardFoldersAddRoute
  '/(protected)/dashboard/tags/$tagName': typeof protectedDashboardTagsTagNameRoute
  '/(protected)/dashboard/folders/': typeof protectedDashboardFoldersIndexRoute
  '/(protected)/dashboard/settings/': typeof protectedDashboardSettingsIndexRoute
  '/(protected)/dashboard/tags/': typeof protectedDashboardTagsIndexRoute
  '/(protected)/dashboard/bookmarks/$id/edit': typeof protectedDashboardBookmarksIdEditRoute
  '/(protected)/dashboard/folders/$id/edit': typeof protectedDashboardFoldersIdEditRoute
  '/(protected)/dashboard/folders/$id/': typeof protectedDashboardFoldersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/bookmarks/add'
    | '/dashboard/folders/add'
    | '/dashboard/tags/$tagName'
    | '/dashboard/folders'
    | '/dashboard/settings'
    | '/dashboard/tags'
    | '/dashboard/bookmarks/$id/edit'
    | '/dashboard/folders/$id/edit'
    | '/dashboard/folders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/bookmarks/add'
    | '/dashboard/folders/add'
    | '/dashboard/tags/$tagName'
    | '/dashboard/folders'
    | '/dashboard/settings'
    | '/dashboard/tags'
    | '/dashboard/bookmarks/$id/edit'
    | '/dashboard/folders/$id/edit'
    | '/dashboard/folders/$id'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/(protected)/dashboard/'
    | '/(protected)/dashboard/bookmarks/add'
    | '/(protected)/dashboard/folders/add'
    | '/(protected)/dashboard/tags/$tagName'
    | '/(protected)/dashboard/folders/'
    | '/(protected)/dashboard/settings/'
    | '/(protected)/dashboard/tags/'
    | '/(protected)/dashboard/bookmarks/$id/edit'
    | '/(protected)/dashboard/folders/$id/edit'
    | '/(protected)/dashboard/folders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/tags/': {
      id: '/(protected)/dashboard/tags/'
      path: '/dashboard/tags'
      fullPath: '/dashboard/tags'
      preLoaderRoute: typeof protectedDashboardTagsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/settings/': {
      id: '/(protected)/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof protectedDashboardSettingsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/folders/': {
      id: '/(protected)/dashboard/folders/'
      path: '/dashboard/folders'
      fullPath: '/dashboard/folders'
      preLoaderRoute: typeof protectedDashboardFoldersIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/tags/$tagName': {
      id: '/(protected)/dashboard/tags/$tagName'
      path: '/dashboard/tags/$tagName'
      fullPath: '/dashboard/tags/$tagName'
      preLoaderRoute: typeof protectedDashboardTagsTagNameRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/folders/add': {
      id: '/(protected)/dashboard/folders/add'
      path: '/dashboard/folders/add'
      fullPath: '/dashboard/folders/add'
      preLoaderRoute: typeof protectedDashboardFoldersAddRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/bookmarks/add': {
      id: '/(protected)/dashboard/bookmarks/add'
      path: '/dashboard/bookmarks/add'
      fullPath: '/dashboard/bookmarks/add'
      preLoaderRoute: typeof protectedDashboardBookmarksAddRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/folders/$id/': {
      id: '/(protected)/dashboard/folders/$id/'
      path: '/dashboard/folders/$id'
      fullPath: '/dashboard/folders/$id'
      preLoaderRoute: typeof protectedDashboardFoldersIdIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/folders/$id/edit': {
      id: '/(protected)/dashboard/folders/$id/edit'
      path: '/dashboard/folders/$id/edit'
      fullPath: '/dashboard/folders/$id/edit'
      preLoaderRoute: typeof protectedDashboardFoldersIdEditRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/bookmarks/$id/edit': {
      id: '/(protected)/dashboard/bookmarks/$id/edit'
      path: '/dashboard/bookmarks/$id/edit'
      fullPath: '/dashboard/bookmarks/$id/edit'
      preLoaderRoute: typeof protectedDashboardBookmarksIdEditRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
  protectedDashboardBookmarksAddRoute: typeof protectedDashboardBookmarksAddRoute
  protectedDashboardFoldersAddRoute: typeof protectedDashboardFoldersAddRoute
  protectedDashboardTagsTagNameRoute: typeof protectedDashboardTagsTagNameRoute
  protectedDashboardFoldersIndexRoute: typeof protectedDashboardFoldersIndexRoute
  protectedDashboardSettingsIndexRoute: typeof protectedDashboardSettingsIndexRoute
  protectedDashboardTagsIndexRoute: typeof protectedDashboardTagsIndexRoute
  protectedDashboardBookmarksIdEditRoute: typeof protectedDashboardBookmarksIdEditRoute
  protectedDashboardFoldersIdEditRoute: typeof protectedDashboardFoldersIdEditRoute
  protectedDashboardFoldersIdIndexRoute: typeof protectedDashboardFoldersIdIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
  protectedDashboardBookmarksAddRoute: protectedDashboardBookmarksAddRoute,
  protectedDashboardFoldersAddRoute: protectedDashboardFoldersAddRoute,
  protectedDashboardTagsTagNameRoute: protectedDashboardTagsTagNameRoute,
  protectedDashboardFoldersIndexRoute: protectedDashboardFoldersIndexRoute,
  protectedDashboardSettingsIndexRoute: protectedDashboardSettingsIndexRoute,
  protectedDashboardTagsIndexRoute: protectedDashboardTagsIndexRoute,
  protectedDashboardBookmarksIdEditRoute:
    protectedDashboardBookmarksIdEditRoute,
  protectedDashboardFoldersIdEditRoute: protectedDashboardFoldersIdEditRoute,
  protectedDashboardFoldersIdIndexRoute: protectedDashboardFoldersIdIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
